version: '3.8'

services:
  db:
    image: postgres
    container_name: user-template-db
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pgdata:/data/postgres
    ports:
      - '8001:5432'

  redis:
    image: redis
    container_name: user-template-redis
    ports:
      - '8002:6379'

volumes:
  pgdata:
