version: '3.8'

services:
  db:
    image: postgres
    container_name: 'user-interface-db'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=user-db
    volumes:
      - pgdata:/data/postgres
    ports:
      - '8001:5432'

  redis:
    image: redis
    ports:
      - '8002:6379'

volumes:
  pgdata:
